version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

volumes:
  mysql_data:
